language: python
python: "2.7"

before_install:
  - sudo apt-get update -qq

install:
  - pip install ansible

script:
  - "{ echo '[defaults]'; echo 'roles_path = ../'; echo 'inventory = inventory'; } >> ansible.cfg"
  - echo localhost > inventory
  - ansible-playbook test.yml --syntax-check
  - ansible-playbook test.yml --connection=local --sudo
  - >
    ansible-playbook test.yml --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
