- hosts: all
  gather_facts: no
  vars_files:
    - defaults/main.yml
  tasks:
    - raw: sudo apt-get -y install python
    - setup: 
    - include: tasks/main.yml
      vars:
        common_users: ["app"]
        common_authorized_keys:
          - https://github.com/haxoza.keys
